Change FRAMEWORK variable to lowercase
Updated framework variable to use lowercase values to match what `render.py` expects.

Previous error:
```
Traceback (most recent call last):
  File "/home/kprashanth/code/dynamo-custom-preprocess-bench/container/render.py", line 132, in <module>
    main()
  File "/home/kprashanth/code/dynamo-custom-preprocess-bench/container/render.py", line 115, in main
    validate_args(args)
  File "/home/kprashanth/code/dynamo-custom-preprocess-bench/container/render.py", line 71, in validate_args
    raise ValueError(
ValueError: Invalid input combination: [framework=VLLM,target=local-dev]
```

Signed-off-by: KrishnanPrash <140860868+KrishnanPrash@users.noreply.github.com>